/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-8-24 上午10:40' with Gradle 2.2.1
 *
 * @author Administrator, @date 16-8-24 上午10:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
